# Server Configuration
server.port=8080

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mockge}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Redis Configuration
# Подключаемся к Redis в Docker контейнере через host.docker.internal
spring.data.redis.host=host.docker.internal
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.timeout=3000ms

# Clerk Configuration
clerk.secret-key=${CLERK_SECRET_KEY:sk_test_SIcShT3DMhnHebPBmUrIaS37Wc2Ono8OSbVuPmYg0Z}
clerk.publishable-key=${CLERK_PUBLISHABLE_KEY:pk_test_bGl0ZXJhdGUtd2lsZGNhdC03NC5jbGVyay5hY2NvdW50cy5kZXYk}
clerk.domain=literate-wildcat-74.clerk.accounts.dev

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.io.mockge=DEBUG
logging.level.org.springframework.security=DEBUG
